---
title: "Mounika"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(tidyverse)
library(broom)
library(knitr)
library(patchwork)
library(rms)
library(reticulate)
```


```{r}
us <- read_csv("df_data/US/us_19_clean.csv")
```

```{r}
us  #temporary will remove later
```


```{r}
full_model <- glm(factor(SED_USE) ~ factor(DEM_GENDER) + DEM_AGE + 
                    factor(DEM_REGION) + factor(DEM_INCOME) + 
                    factor(DEM_GENHEALTH) + factor(DAST_10) + 
                    factor(DEM_RACE_AIAN) + 
                    factor(DEM_RACE_ASIAN) + factor(DEM_RACE_BLACK) + 
                    factor(DEM_RACE_NHPI) + factor(DEM_RACE_WHITE) + 
                    factor(DEM_RACE_OTH) + factor(DEM_MARITAL) + 
                    factor(DEM_EDU) + factor(DEM_STDNT) + factor(DEM_VET) + 
                    factor(DEM_EMPLOY) + factor(DEM_HEALTH) + 
                    factor(DEM_EMPLOY) + factor(DEM_INSUR) + factor(DEM_AGE10),
                     data = us,
                      family = "binomial")

backward_aic <- step(full_model, direction = "backward")

n <- 29873

backward_bic <- step(full_model, k = log(n), direction = "backward")
```
```{r}
tidy(backward_aic)

tidy(backward_bic)
```

